# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk3-Ex-DBI
version:      3.1
version_from: lib/Gtk3/Ex/DBI.pm
installdirs:  site
requires:
    DBI:                           1.3
    Gtk3:                          1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
